# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9ba6802b6658ed75197d542f115373094ea889d7040d53a4fcc1760fc82370ba0c77f4884e37d5615cc09e55211f6554bce158e492fdd800fa8d59709ec656

test:
  secret_key_base: 33db1ef47905ba67d6659437e1642b244044ac40d26f671257e603ad32d064360c64ad0cfed951841b13669d76a0fe81a46c0324eec4042b718e5e95a7870fdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
